language: php

os:
  - linux
  # - osx

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64

services:
  - docker
  
before_install:
  # Run TestSuite
  - cd ./test_suite
  - docker-compose up -d
  - cd ..
  - sleep 60  # Wait for TestSuite is ready
  - composer install
  - composer dump-autoload
  
php:   
#  - "5.6"
  - "7.3"
#  - "nightly"  # nightly build

script:
  - php vendor/phpunit/phpunit/phpunit ./tests/EncryptionTest.php
  - php vendor/phpunit/phpunit/phpunit ./tests/TestAgent.php
  - php vendor/phpunit/phpunit/phpunit ./tests/TestFuturePromise.php
  - php vendor/phpunit/phpunit/phpunit ./tests/TestLocks.php
  - php vendor/phpunit/phpunit/phpunit ./tests/TestMessages.php
  - php vendor/phpunit/phpunit/phpunit ./tests/TestMicroledgers.php
  - php vendor/phpunit/phpunit/phpunit ./tests/TestStorages.php
  - php vendor/phpunit/phpunit/phpunit ./tests/TestWallet.php
  - php vendor/phpunit/phpunit/phpunit ./tests/TestPairwise.php
